### ISSUE TITLE
Remote entity doesn't exist

### ISSUE THREAD

**Issue by dgrothman** [unfoldedcircle/integration-node-library#33]
I see that the remote entity does not exist. Is it possible to get it added to the repo?

**Comment by zehnm** [comment]
Absolutely, the Node.js library requires a major update for feature parity with the Python API wrapper.

**Comment by dgrothman** [comment]
I wrote the entity and would be willing to help, how would I go about getting access to be able to push changes for review?

**Comment by zehnm** [comment]
I've updated the repository with [contribution guidelines](https://github.com/unfoldedcircle/integration-node-library/blob/main/CONTRIBUTING.md) and made the first refactoring to catch up with our Python integration library in PR #35. The most notable changes and enhancements are:
- setup flow handler callback, no more manual WebSocket calls.
- entity command handler callback.
- missing entity features and options

The old event notifications for entity commands and setup flow handling are still present and  _should_ be triggered if no callback handler is set.

Since I require the remote-entity for a new integration as well, I'll add it tomorrow, unless you open a pull request today.

**Comment by zehnm** [comment]
Implemented in PR #36
